server:
  port: 8082

spring:
  application:
    name: examination-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/examdb

management:
  endpoints:
    web:
      exposure:
        include: "*"
